name: CI
on: [pull_request, workflow_dispatch]
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
          - os: windows-11-arm
          - os: macos-latest
          - os: ubuntu-latest
      fail-fast: false
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v6
      - uses: mlugg/setup-zig@v2
      - run: zig build ci -Dci --summary all
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - if: ${{ matrix.os == 'ubuntu-latest' }}
        name: getversion
        id: version
        run: echo "version=$(cat zig-out/version-release)" >> $GITHUB_OUTPUT
      - if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: actions/upload-artifact@v7
        with:
          name: hew-${{ steps.version.outputs.version }}-archives
          path: |
            zig-out/hew-aarch64-linux.tar.gz
            zig-out/hew-aarch64-macos.tar.gz
            zig-out/hew-aarch64-windows.zip
            zig-out/hew-arm-linux.tar.gz
            zig-out/hew-powerpc64le-linux.tar.gz
            zig-out/hew-riscv64-linux.tar.gz
            zig-out/hew-s390x-linux.tar.gz
            zig-out/hew-x86-linux.tar.gz
            zig-out/hew-x86-windows.zip
            zig-out/hew-x86_64-linux.tar.gz
            zig-out/hew-x86_64-macos.tar.gz
            zig-out/hew-x86_64-windows.zip
