name: Package Tester
on:
  workflow_dispatch:
    inputs:
      package:
        description: 'The package to test'
        required: true
        type: string

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
          - os: windows-11-arm
          - os: macos-latest
          - os: ubuntu-latest
      fail-fast: false
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v6
      - uses: mlugg/setup-zig@v2
      - name: Build hew
        run: zig build

      # --------------------------------------------------------------------------------
      # Windows
      # --------------------------------------------------------------------------------
      - name: Configure bin path (Windows)
        if: runner.os == 'Windows'
        run: |
          $env:PATH = "$env:PATH;${{ github.workspace }}\test\bin"
          .\zig-out\bin\hew.exe new-bin-path --app-data ${{ github.workspace }}\test\appdata ${{ github.workspace }}\test\bin
      - name: Install package (Windows)
        if: runner.os == 'Windows'
        run: |
          $env:PATH = "$env:PATH;${{ github.workspace }}\test\bin"
          .\zig-out\bin\hew.exe install --app-data ${{ github.workspace }}\test\appdata --non-interactive --allow-shadow ${{ github.event.inputs.package }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # --------------------------------------------------------------------------------
      # Not Windows
      # --------------------------------------------------------------------------------
      - name: Configure bin path (Posix)
        if: runner.os != 'Windows'
        run: PATH="$PATH:${{ github.workspace }}/test/bin" ./zig-out/bin/hew new-bin-path --app-data ${{ github.workspace }}/test/appdata ${{ github.workspace }}/test/bin
      - name: Install package (Posix)
        if: runner.os != 'Windows'
        run: PATH="$PATH:${{ github.workspace }}/test/bin" ./zig-out/bin/hew install --app-data ${{ github.workspace }}/test/appdata --non-interactive --allow-shadow ${{ github.event.inputs.package }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
